#!/bin/bash

# Create 2e5 fq reads of length 50  from EColi genome with NO errors
./simReads.pl EColi_genome.fa 0.2 0 50  0  > EColi_rRNA.fq
# Create 5e4 fq reads of length 50  from rRNA_modified with NO errors
# rRNA_modified is the sequence rRNA_CRUnit with the lines containing 
# N's removed 
./simReads.pl rRNA_modified.fa 0.05 0 50 0  >>  EColi_rRNA.fq

# Check --trimQ: add low quality reads (low quality 9 <-> 25)
# check also the low quality threshold
# 9 reads: 
# Option ENDSFRAC (-p 5): 4 discarded, 4 trimmed, 1 left "as is"
echo "@ read LOWQ trim: 5-44
CAGTTCTTTGGTGTAGATGGAGCAGGACGGGATACCCATACCGTGACCCA
+position: -19377
99999IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII99999
@ read 108110 LOWQ trim: 1-48
CAGATAAATGCGAATGAATGGGTAACACTGGAGCTTTTAATGGCTGTAAC
+position: -4142524
9IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII9
@ read 108111 LOWQ discard
AGCGTGACGGTGTAACGCCCGCCTTTTGATGACTGGGTTTCAAAGAAACG
+position: -3336785
99IIIIIIIIIIII9IIIIIIII9IIIIIIIII9IIIIIIIIIIIIII99
@ read 108112  LOWQ 4-49
ACCGGTAATGATACCCGCCAGTACACCCATGTTTATTTCTGGGTTGATGG
+position: -4548423
9999IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@ read 1081133  LOWQ 0-48
GTACATTGATGAGCAACATGGGGCTTGAACTGGCGCTGAAACAGTTAGGA
+position: -144740
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII9
@ read 108114 LOWQ discard
CTTAACCTGAACATTGAAGAGTTTAAAGGCGAGCAGTTACGCGTGACGGG
+position: 5075572
IIIIIIIIIIIIIIIIIIIII9999999IIIIIIIIIIIIIIIIIIIIII
@ read 108116 LOWQ discard
TCAGGGTGCAGCGGTAGCGCCAGTTTCCAGTCCATCGCCATTTTGTAGAC
+position: 1750468
IIIIIIIIIIII9III9IIIIII9IIIIIIIIIIIIIIIIIIIIIIIIII
@ read 108117 LOWQ accepted
ATTCACTGTAAGCGCGGTCTGGTATGGGGCGAGCTGGAATTTGTACTGCC
+position: 1091320
IIIIIIIIIIIIIIIIIIIIIII9IIIIIIIIIIIIIIIIIIIIIIIIII
@ read 108118 LOWQ discard
CAGCAAAATCATGCCGAGGAAGGCAATGCAAAGATAGTTGCCGAACGGAT
+position: -4651833
9IIIIIIIIIII9IIIIIIIIIII9IIIIIIII9IIIIIIIIIIIIIII9"  >> EColi_rRNA.fq

# Check --trimN: add reads with N's, at the ends and in the middle
# 10 reads.
# Option STRIP: 7 trimmed, 3 discarded.
echo "@ read 1037  trimN: 2-47
NNTCGACACAAGAAAATGCGCCAATTTTGAGCCAGACCCCAGTTACGCNN
+position: -2044610
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@ read 1038 trimN: 17 - 49
AAAAAACGGTCGTGGTNGGCTACTGTTATTAAAGCGTTGGCTACAAAAAG
+position: 1361068
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@ read 1039 discard N
CCAACGGACNATGGAAGTGCTNCGGCTGGNGTTTTTATCCTCCGGCATTC
+position: -4282223
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@ read 1040 discard N
GCAAACGTATTTATGGCGACNNNNNNNCCGGTCATCAGGCCGATAAACGC
+position: 3171482
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@ read 1041i trimN: 2-49
NNCATGCGCGTTCACTGCCCGCGATCCAGGATATTTTTTCCAGGGGGACC
+position: -86494
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@ read 1042 trimN: 0 - 46
TGTCTGGCAACCTGATTCATCAGGCTTTGCGTAAGCGGAACGATTAANNN
+position: -3861809
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@ read 1043 trimN: 0 - 48 vs discard
AATCTGAAACGAAANCTGACAGCGNNCCCCGCTTCTGACAAAATAGGCGN
+position: -4685876
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@ read 1044 trimN: 2 - 46 vs 4 - 46
NNANATGATCCTGGTCTGCAATAATCGTAAAGGGGCCGTCAGCGTGTNNN
+position: 1377584
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@ read 1045 trimN: 12 - 43
CGCCATNCCGANAATGATTGCTTTCGCCATATGGGTACGTCCGGNGATCC
+position: -2919586
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@ read 1046 accepted vs trimN: 13 - 49
CCCCTCTGCANNNCNCAATAATTTCATCGAGGAATCCGTTGCTTCGGGCT
+position: -3548964
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII" >> EColi_rRNA.fq

gzip EColi_rRNA.fq

